{{- if .Values.openid.enabled }}
{{ $requiredConfig := pick .Values.openid.config "client_id" "client_secret" "redirect_url" "email_domains" "cookie_secret" "oidc_issuer_url" }} # ... all the ones we require
{{- range $requiredConfig }}
    {{ if .|empty }}
    fail "all default odic options must be entered if enabled"
    {{- end }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "labels" . | indent 4 }}
  name: "{{ .Values.name }}-oauth"
  namespace: {{ .Release.namespace }}
data:
  oauth2_proxy.cfg: |
{{- range $key, $val := .Values.openid.config }}
    {{ $key }} = {{ $val | quote }}
{{- end }}
{{- end }}
