
{{- if .Values.storage.aws.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.storage.name }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: O-Fish Bucket
data:
  AWS_ACCESS_KEY_ID: {{ .Values.storage.aws.accessKey | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.storage.aws.region | b64enc }}
  AWS_S3_BUCKET: {{ .Values.storage.aws.bucket | b64enc }}
  AWS_S3_ENDPOINT: {{ .Values.storage.aws.endpoint | b64enc}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.aws.secretKey | b64enc }}
type: Opaque
{{- end}}